repos:
  - repo: https://github.com/fastai/nbdev
    rev: 2.3.11
    hooks:
      - id: nbdev_clean
        args:
          - --clear_all
      - id: nbdev_export
  # - repo: https://github.com/python-poetry/poetry
  #   rev: 1.5.0 # add version here
  #   hooks:
  #     - id: poetry-check
  #     - id: poetry-lock
  #     - id: poetry-export
