# prevent to commit files that have not been pre-processed, not to fix issues before commiting.
repos:
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.5.3
    hooks:
      - id: nbqa-black
        files: \.(ipynb)$
        verbose: true
  - repo: https://github.com/fastai/nbdev
    rev: 2.3.11
    hooks:
      - id: nbdev_clean
        args:
          - --clear_all
      - id: nbdev_export
        additional_dependencies: [black]
